Append apply to sync branch to svn action
ArielAirOne/.github pull request #7
Opened 2021-02-07 14:06 UTC by acearth

2021-02-08 03:37 UTC, KengoTODA requested changes

2021-02-08 03:37 UTC, KengoTODA commented on workflow-templates/sync-git-to-svn.yml
> +          node-version: '${{ steps.nvm.outputs.NVMRC }}'
The target repo probably has no `.nvmrc` file. I guess we can remove these lines.

2021-02-08 03:37 UTC, KengoTODA commented on workflow-templates/sync-git-to-svn.yml
> +          svn-url: ${{ YOUR_SPECIFIC_SVN_BRANCH_URL }}
Could you add a comment to provide an example? It's possible that user got confused when they use the URL of repository viewer, not the raw Subversions' WebDAV.

2021-02-08 06:30 UTC, acearth commented
Improved based on review.

All change required parts add TODO comment

2021-02-10 04:03 UTC, KengoTODA approved these changes

2021-02-10 04:03 UTC, merged